[package]
name = "mandelbrot-example-rust"
version = "0.1.0"
authors = ["Phil Kedy <phil.kedy@gmail.com>"]
edition = "2018"
description = "Renders the Mandelbrot set in Rust"
license = "Apache-2.0"

[dependencies]
wapc-guest = "0.4.0"
serde = { version = "1.0.115" , features = ["derive"] }
serde_json = "1.0.57"
serde_derive = "1.0.115"
serde_bytes = "0.11.5"
rmp-serde = "0.14.4"
log = { version="0.4.11", features =["std","serde"]}
lazy_static = "1.4.0"

[dev-dependencies]
structopt = "0.3.17"
serde_json = "1.0.57"
base64 = "0.12.3"

[profile.release]
# Optimize for small code size
opt-level = "s"
lto = true
